PFI_STATUS_NONE = "none"
PFI_STATUS_PENDING_APPROVAL = "pending_approval"
PFI_STATUS_APPROVED = "approved"
PFI_STATUS_HELD = "held"

PFI_STATUSES = (
    PFI_STATUS_NONE,
    PFI_STATUS_PENDING_APPROVAL,
    PFI_STATUS_APPROVED,
    PFI_STATUS_HELD,
)

